<RunenMasterScreens>:

	# 1e screen vd App
	WelcomeScreen:
		name: "welcomescreen"
	MenuScreen:
		name: "menuscreen"
	QuizzScreen:
		name: "quizzscreen"
	VragenScreen:
		name: "vragenscreen"
	VragenScreeneen:
		name:"vragenscreeneen"
	VragenScreentwee:
		name:"vragenscreentwee"
	ResultScreen:
		name: "resultscreen"
	CollegeSymbolsScreen:
		name: "collegesymbolsscreen"
	CollegeNamesScreen:
		name: "collegenamesscreen"
	StatsScreen:
		name:"statsscreen"

