<RunenMasterScreens>:

	# 1e screen vd App
	WelcomeScreen:
		name: "welcomescreen"
	MenuScreen:
		name: "menuscreen"
	QuizzScreen:
		name: "quizzscreen"
	VragenScreen:
		name: "vragenscreen"
	VragenScreen1:
		name:"vragenscreen1"
	VragenScreen2:
		name:"vragenscreen2"
	ResultScreen:
		name: "resultscreen"
	CollegeSymbolsScreen:
		name: "CollegeSymbols_screen"
	CollegeNamesScreen:
		name: "CollegeNames_screen"

