#: import vragen_2 vragen_2

<AntwButton@Button>
	background_color: 1,1,1,0
	background_normal:""
	canvas.before:
		Color:
			rgba: [1,1,1,1]
		RoundedRectangle:
			size: self.size
			pos:self.pos
			radius: [8]

	font_size: dp(14)
	halign:"left"
	valign:"center"
	color:0,0,0,1

<VragenScreen2>:

	canvas:
		Color:
			rgba: [0,0,1,1]
		Rectangle:
			size:self.width, self.height
			source:"Pics/alternative.jpg"

	BoxLayout:
		orientation: "vertical"
		size_hint:(1,.2)
		pos_hint:{"center_y":.75}

		Label:
			text: "Training\n Meaning of Runes"
			halign:"center"
			font_size:dp(24)

	BoxLayout:
		orientation:"vertical"
		size_hint:(1,.18)
		pos_hint:{"center_y":.5}

		Image:
			id:_PictureChoice
			source:""

			canvas.before:
				Color:
					rgba:1,1,1,1
				Ellipse:
					size: 100,100
					pos:self.parent.center_x-50,self.parent.center_y
		Label:
			text:""
			font_size: dp(14)

		Label:
			id:_Vraag_label
			text:"What's the meaning\nthis rune ...?"
			font_size: dp(18)
			halign:"center"
			valign:"bottom"
			color:1,1,1,1

	BoxLayout:
		orientation: "vertical"
		size_hint:(1,.42)

		GridLayout:
			cols:2
			padding:20
			spacing:20
			size_hint:(1,.4)

			AntwButton:
				id: _antw1
				text: ""
				#font_size: dp(14)
				text_size:120,None
				on_release:
					root.ClearButtons()
					self.background_color = 1,0,0,.3
					root.PressedButton(self.text)

			AntwButton:
				id: _antw2
				text: ""
				text_size:120,None
				on_release:
					root.ClearButtons()
					self.background_color = 1,0,0,.3
					root.PressedButton(self.text)
			AntwButton:
				id: _antw3
				text: ""
				text_size:120,None
				on_release:
					root.ClearButtons()
					self.background_color = 1,0,0,.3
					root.PressedButton(self.text)
			AntwButton:
				id: _antw4
				text: ""
				text_size:120,None
				on_release:
					root.ClearButtons()
					self.background_color = 1,0,0,.3
					root.PressedButton(self.text)

		Button:
			text: "<< Submit >>"
			font_size: dp(14)
			size_hint:(.33,.05)
			background_color:1,1,1,0.1
			pos_hint:{"center_x":.5,"top":1}
			on_release:
				root.ClearButtons()
				root.SubmittAnswer()

	AnchorLayout:
		anchor_x: "right"
		anchor_y: "top"

		BoxLayout:
			orientation: 'horizontal'
			padding:15
			size_hint: None, None
			size: self.minimum_size

			AnchorButton:
				text: "Menu"
				font_size:dp(14)
				on_release:
					# voortijdig afbreken dus reset quizzvariabelen
					root.CleanUp()
					root.manager.current="menuscreen"

			AnchorButton:
				text: "Quit"
				font_size:dp(14)
				on_release:
					quit()


