#: import vragentwee vragentwee

<AntwButton@Button>
	background_color: 1,1,1,0
	background_normal:""
	canvas.before:
		Color:
			rgba: [1,1,1,1]
		RoundedRectangle:
			size: self.size
			pos:self.pos
			radius: [8]

	font_size: dp(14)
	halign:"left"
	valign:"center"
	color:0,0,0,1

<VragenScreentwee>:

	canvas:
		Color:
			rgba: [0,0,1,1]
		Rectangle:
			size:self.width, self.height
			source:"Pics/Olaus.jpg"

	BoxLayout:
		orientation: "vertical"
		size_hint:(1,.2)
		pos_hint:{"center_y":.75}

		Label:
			text: "Test\nMeaning of Runes"
			halign:"center"
			font_size:dp(24)

	BoxLayout:
		orientation:"vertical"
		size_hint:(1,.18)
		pos_hint:{"center_y":.63}

		Image:
			id:_PictureChoice
			source:""
			background_color: 1,1,1,0
			background_normal:""

			canvas.before:
				Color:
					rgba:1,1,1,1
				Ellipse:
					size: 180,180
					pos:self.parent.center_x-90,self.parent.center_y-180

			size_hint:None,None
			width:120
			height:120
			allow_stretch:True
			keep_ratio:False
			pos_hint:{"center_x":.5}

	BoxLayout:
		orientation: "vertical"
		size_hint:(1,.3)
		pos_hint:{"center_y":.45}

		Label:
			id:_Vraag_label
			text:"What's the meaning\nthis rune ...?"
			font_size: dp(18)
			halign:"center"
			valign:"bottom"
			color:1,1,1,1

	BoxLayout:
		orientation: "vertical"
		size_hint:(1,.42)


		GridLayout:
			cols:2
			padding:20
			spacing:20
			size_hint:(1,.4)

			AntwButton:
				id: _antw1
				text: ""
				#font_size: dp(14)
				text_size:240,None
				on_release:
					root.ClearButtons()
					self.background_color = 1,0,0,.3
					root.PressedButton(self.text)

			AntwButton:
				id: _antw2
				text: ""
				text_size:240,None
				on_release:
					root.ClearButtons()
					self.background_color = 1,0,0,.3
					root.PressedButton(self.text)
			AntwButton:
				id: _antw3
				text: ""
				text_size:240,None
				on_release:
					root.ClearButtons()
					self.background_color = 1,0,0,.3
					root.PressedButton(self.text)
			AntwButton:
				id: _antw4
				text: ""
				text_size:240,None
				on_release:
					root.ClearButtons()
					self.background_color = 1,0,0,.3
					root.PressedButton(self.text)

	#	Button:
	#		text: "<< Submit >>"
	#		font_size: dp(14)
	#		size_hint:(.33,.05)
	#		background_color:1,1,1,0.1
	#		pos_hint:{"center_x":.5,"top":1}
	#		on_release:
	#			root.ClearButtons()
	#			root.SubmittAnswer()

		Button:
			id:_ButtonStart
			text:"Submit"
			font_size:dp(14)
			halign:"center"
			color: 1,1,1,1
			background_color: 1,1,1,0
			size_hint: (.25,.15)
			pos_hint:{"center_x":.5, "center_y":.075}
			on_press:
				self.color=[0,0,0,1]
				root.ClearButtons()
				root.SubmittAnswer()
			canvas.before:
				Color:
					rgba: 1,1,1,.5
				Ellipse:
					size: 130, 130
					pos:self.center_x-65,self.center_y-65

	ActionBar:
		size:self.width, 50
		pos_hint:{"top":1}

		canvas:
			Color:
				rgba:1,1,1,1
			Rectangle:
				size:self.size
				pos:self.pos

		ActionView:
			id: _toolbar
			spacing:40

			ActionPrevious:
				color:0,0,0,1
				title:"[size=14]Master of Runes[/size]"
				markup:True
				with_previous:False
				app_icon:"icon.png"
				app_icon_height:50
				app_icon_width:50

			ActionButton:
				icon:"Pics/home.png"
				background_color:1,0,1,.85
				text:"Stats"
				font_size:dp(14)
				on_release:
					root.manager.current="menuscreen"

			ActionButton:
				icon:"Pics/close.png"
				background_color:1,0,1,.85
				text:"Exit"
				font_size:dp(14)
				on_release:
					quit()



